# Generated by Django 5.2.1 on 2025-05-14 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_description_product_price'),
        ('core', '0002_product_sku'),
    ]

    operations = [
    ]
